### ISSUE TITLE
Contamination in IsolationForest

### ISSUE THREAD

**Issue by akalino** [aolimelo/kged#2]
In the initialization of the isolation forest, the default parameters are used, which would be contamination=0.1 if using scikit-learn < 0.22. Should this be the value used, or should the code reflect the choice of 'auto'? See the documentation and future updates to scikit-learn below:

contamination : float in (0., 0.5), optional (default=0.1)
The amount of contamination of the data set, i.e. the proportion of outliers in the data set. Used when fitting to define the threshold on the decision function. If ‘auto’, the decision function threshold is determined as in the original paper.

Changed in version 0.20: The default value of contamination will change from 0.1 in 0.20 to 'auto' in 0.22.

 I didn't see any discussion of varying the contamination parameter in the paper.

Thanks.

**Comment by aolimelo** [comment]
I ran the experiments with scikit-learn < 0.22 and the default settings. In that case contamination=0.1.
