### ISSUE TITLE
the result of data eswc is lower than the result in paper

### ISSUE THREAD

**Issue by ghost** [aolimelo/kged#3]
Hi~It's an interesting job to follow, and it is so nice to provide a wonderful code which is easy to understand and reuse. However, I meet a problem when I use it: the FMRR values of eswc with kind 1 errors are lower than the values in the paper:
I get fMRR = 0.634, FMR = 36.256, however, ROCAUC = 0.991. 

I would very appreciate it if you can help me : )

**Comment by aolimelo** [comment]
What parameter settings did you use? Are you sure they are the same as those reported in the experiments section?

**Comment by ghost** [comment]
Thanks for your reply! !The parameter settings I used are the same as those reported in the experiment section, for eswc:
python detect_errors.py data/eswc2015-errdet-ek1-p0.010000.npz -m patybred  -sp learned-model.pkl  -ut
mpl = 2
max-feats =10
neg-weight =1
max-path-length =2
max-paths-per-level =99999999
minimum-support =0.001
classifier =rf

**Comment by aolimelo** [comment]
I think the problem might the max-paths-per-level value you set. I think it should be 1000, in general very large numbers don't work very well as most paths of length 2 or greater are not relevant and end up harming performance.

**Comment by ghost** [comment]
Thanks for your patience~ I try to set the max-paths-per-level value to be 1000. However, I get a worse result:
 FMRR = 0.602712    FMR = 125.463415   ROCAUC = 0.969475

**Comment by ghost** [comment]
Hi~ I get the correct result by rewriting the evaluation function following your paper~
1. The model code is right, efficient and powerful!!! Thank you for your open source~
2. I change "id_rank = rankdata(scores)"  to "id_rank = rankdata(scores, method='ordinal')"
3. I change the defination of "filter_ranks" to :
`def filter_ranks(ranks):
    filtered_ranks = np.zeros(len(ranks))
    filtered = 0
    count = 0
    for i in range(len(ranks)):
        count += 1
        filtered_ranks[i] = ranks[i]-(count-1)
    return filtered_ranks`
4. And I get the result:
              | eswc |  iswc | nobel | aifb |
PaBRED | 0.831 | 0.980| 0.200 | 0.173| (in paper)
PaBRED | 0.781 | 0.980| 0.200 | 0.173| ( I get )
*the command is:python detect_errors.py data\xxx-errdet-ek1-p0.010000.npz -mppl 1000 -m pabred
Your help is greatly appreciated. I'd like to wish you every success.
