### ISSUE TITLE
The usage of rank_facts.py

### ISSUE THREAD

**Issue by ghost** [aolimelo/kged#4]
Hi~ I am not sure the usage of rank_facts.py. The outputs of it are not used in detect_errors.py.

I urgently want to know some details of your method. If you can give me your contact way, I will be greatly appreciated~

**Comment by aolimelo** [comment]
Hi, sorry for the delay. I've been on holidays and just got back today. 
Indeed rank_facts.py is not used by detect_errors.py. The rank_facts.py script takes a KG, learns a triple scoring model and produce a list of all relation assertions in the KG ranked by the learned model. The detect_errors.py, on the other hand, takes a KG with synthesized errors, goes through a similar process of learning the model and ranking the triples, and uses the ranks of the synthesized errors to compute the evaluation measures.

**Comment by ghost** [comment]
Thank you very much~
